# docker-compose.yml

version: "3.5"
services:
  backend:
    build:
      context: ./backend
    restart: always
    ports:
      - 4000:4000
    networks:
      - db-net
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
    restart: always
    ports:
      - 3000:3000
  db:
    image: mysql:8.0.20
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: edurootroot
    networks:
      - db-net
    ports:
      - 8086:3306

networks:
  db-net:
